<?php

return [
    'brands' => [
        'apple',
        'samsung_a',
        'samsung_note',
        'samsung_s',
        'xiaomi_mi',
        'xiaomi_redmi',
        'xiaomi_poco',
        'oppo_find',
        'oppo_reno',
        'oppo_a',
        'huawei_p',
        'huawei_mate',
        'huawei_nova',
        'honor',
        'google_pixel',
        'tcl'
    ],

    'apple' => [
        'iPhone 6',
        'iPhone 6 Plus',
        'iPhone 6S',
        'iPhone 6S Plus',
        'iPhone SE (1st generation)',
        'iPhone 7',
        'iPhone 7 Plus',
        'iPhone 8',
        'iPhone 8 Plus',
        'iPhone X',
        'iPhone XS',
        'iPhone XS Max',
        'iPhone XR',
        'iPhone 11',
        'iPhone 11 Pro',
        'iPhone 11 Pro Max',
        'iPhone SE (2nd generation)',
        'iPhone 12 mini',
        'iPhone 12',
        'iPhone 12 Pro',
        'iPhone 12 Pro Max',
        'iPhone 13 mini',
        'iPhone 13',
        'iPhone 13 Pro',
        'iPhone 13 Pro Max',
        'iPhone SE (3rd generation)',
        'iPhone 14',
        'iPhone 14 Plus',
        'iPhone 14 Pro',
        'iPhone 14 Pro Max',
        'iPhone 15',
        'iPhone 15 Plus',
        'iPhone 15 Pro',
        'iPhone 15 Pro Max',
        'iPhone 16',
        'iPhone 16 Plus',
        'iPhone 16 Pro',
        'iPhone 16 Pro Max'
    ],

    'samsung_a' => [
        'Samsung Galaxy A01',
        'Samsung Galaxy A10',
        'Samsung Galaxy A10s',
        'Samsung Galaxy A11',
        'Samsung Galaxy A12',
        'Samsung Galaxy A20',
        'Samsung Galaxy A20e',
        'Samsung Galaxy A20s',
        'Samsung Galaxy A21',
        'Samsung Galaxy A21s',
        'Samsung Galaxy A22',
        'Samsung Galaxy A22 5G',
        'Samsung Galaxy A30',
        'Samsung Galaxy A30s',
        'Samsung Galaxy A31',
        'Samsung Galaxy A32',
        'Samsung Galaxy A32 5G',
        'Samsung Galaxy A40',
        'Samsung Galaxy A41',
        'Samsung Galaxy A50',
        'Samsung Galaxy A50s',
        'Samsung Galaxy A51',
        'Samsung Galaxy A51 5G',
        'Samsung Galaxy A52',
        'Samsung Galaxy A52 5G',
        'Samsung Galaxy A52s 5G',
        'Samsung Galaxy A53 5G',
        'Samsung Galaxy A60',
        'Samsung Galaxy A70',
        'Samsung Galaxy A70s',
        'Samsung Galaxy A71',
        'Samsung Galaxy A71 5G',
        'Samsung Galaxy A72',
        'Samsung Galaxy A80',
        'Samsung Galaxy A90 5G'
    ],

    'samsung_note' => [
        'Samsung Galaxy Note',
        'Samsung Galaxy Note II',
        'Samsung Galaxy Note 3',
        'Samsung Galaxy Note 3 Neo',
        'Samsung Galaxy Note 4',
        'Samsung Galaxy Note Edge',
        'Samsung Galaxy Note 5',
        'Samsung Galaxy Note 7',
        'Samsung Galaxy Note FE (Fan Edition)',
        'Samsung Galaxy Note 8',
        'Samsung Galaxy Note 9',
        'Samsung Galaxy Note 10',
        'Samsung Galaxy Note 10+',
        'Samsung Galaxy Note 10 Lite',
        'Samsung Galaxy Note 20',
        'Samsung Galaxy Note 20 Ultra'
    ],

    'samsung_s' => [
        'Samsung Galaxy S',
        'Samsung Galaxy S II',
        'Samsung Galaxy S III',
        'Samsung Galaxy S4',
        'Samsung Galaxy S5',
        'Samsung Galaxy S6',
        'Samsung Galaxy S6 Edge',
        'Samsung Galaxy S6 Edge+',
        'Samsung Galaxy S7',
        'Samsung Galaxy S7 Edge',
        'Samsung Galaxy S8',
        'Samsung Galaxy S8+',
        'Samsung Galaxy S9',
        'Samsung Galaxy S9+',
        'Samsung Galaxy S10',
        'Samsung Galaxy S10+',
        'Samsung Galaxy S10e',
        'Samsung Galaxy S10 5G',
        'Samsung Galaxy S20',
        'Samsung Galaxy S20+',
        'Samsung Galaxy S20 Ultra',
        'Samsung Galaxy S20 FE',
        'Samsung Galaxy S21',
        'Samsung Galaxy S21+',
        'Samsung Galaxy S21 Ultra',
        'Samsung Galaxy S21 FE',
        'Samsung Galaxy S22',
        'Samsung Galaxy S22+',
        'Samsung Galaxy S22 Ultra',
        'Samsung Galaxy S23',
        'Samsung Galaxy S23+',
        'Samsung Galaxy S23 Ultra'
    ],


    'xiaomi_mi' => [
        'Xiaomi Mi 1',
        'Xiaomi Mi 2',
        'Xiaomi Mi 3',
        'Xiaomi Mi 4',
        'Xiaomi Mi 5',
        'Xiaomi Mi 5s',
        'Xiaomi Mi 5s Plus',
        'Xiaomi Mi 6',
        'Xiaomi Mi 6X',
        'Xiaomi Mi 8',
        'Xiaomi Mi 8 Pro',
        'Xiaomi Mi 8 Lite',
        'Xiaomi Mi 9',
        'Xiaomi Mi 9 SE',
        'Xiaomi Mi 9T',
        'Xiaomi Mi 9T Pro',
        'Xiaomi Mi 10',
        'Xiaomi Mi 10 Pro',
        'Xiaomi Mi 10T',
        'Xiaomi Mi 10T Pro',
        'Xiaomi Mi 11',
        'Xiaomi Mi 11 Lite',
        'Xiaomi Mi 11 Ultra',
        'Xiaomi 12',
        'Xiaomi 12 Pro',
        'Xiaomi 12S Ultra',
        'Xiaomi 13',
        'Xiaomi 13 Pro',
        'Xiaomi 13 Ultra'
    ],

    'xiaomi_redmi' => [
        'Xiaomi Redmi 1',
        'Xiaomi Redmi 1S',
        'Xiaomi Redmi 2',
        'Xiaomi Redmi 2 Prime',
        'Xiaomi Redmi 3',
        'Xiaomi Redmi 3S',
        'Xiaomi Redmi 4',
        'Xiaomi Redmi 4X',
        'Xiaomi Redmi 5',
        'Xiaomi Redmi 5 Plus',
        'Xiaomi Redmi 6',
        'Xiaomi Redmi 6 Pro',
        'Xiaomi Redmi 7',
        'Xiaomi Redmi 7A',
        'Xiaomi Redmi 8',
        'Xiaomi Redmi 8A',
        'Xiaomi Redmi 9',
        'Xiaomi Redmi 9A',
        'Xiaomi Redmi 9C',
        'Xiaomi Redmi 9T',
        'Xiaomi Redmi 10',
        'Xiaomi Redmi 10A',
        'Xiaomi Redmi 10C',
        'Xiaomi Redmi 12',
        'Xiaomi Redmi Note 5',
        'Xiaomi Redmi Note 6 Pro',
        'Xiaomi Redmi Note 7',
        'Xiaomi Redmi Note 8',
        'Xiaomi Redmi Note 8 Pro',
        'Xiaomi Redmi Note 9',
        'Xiaomi Redmi Note 9 Pro',
        'Xiaomi Redmi Note 10',
        'Xiaomi Redmi Note 10 Pro',
        'Xiaomi Redmi Note 11',
        'Xiaomi Redmi Note 11 Pro',
        'Xiaomi Redmi Note 12',
        'Xiaomi Redmi Note 12 Pro'
    ],

    'xiaomi_poco' => [
        'Xiaomi Poco F1',
        'Xiaomi Poco F2 Pro',
        'Xiaomi Poco F3',
        'Xiaomi Poco F4',
        'Xiaomi Poco X2',
        'Xiaomi Poco X3',
        'Xiaomi Poco X3 Pro',
        'Xiaomi Poco X4',
        'Xiaomi Poco M2',
        'Xiaomi Poco M3',
        'Xiaomi Poco M4 Pro',
        'Xiaomi Poco M5'
    ],



    'oppo_find' => [
        'Oppo Find 5',
        'Oppo Find 7',
        'Oppo Find 7a',
        'Oppo Find 9',
        'Oppo Find X',
        'Oppo Find X2',
        'Oppo Find X2 Pro',
        'Oppo Find X3',
        'Oppo Find X3 Pro',
        'Oppo Find X5',
        'Oppo Find X5 Pro',
        'Oppo Find N'
    ],

    'oppo_reno' => [
        'Oppo Reno',
        'Oppo Reno 10x Zoom',
        'Oppo Reno 2',
        'Oppo Reno 2F',
        'Oppo Reno 3',
        'Oppo Reno 3 Pro',
        'Oppo Reno 4',
        'Oppo Reno 4 Pro',
        'Oppo Reno 5',
        'Oppo Reno 5 Pro',
        'Oppo Reno 5 Pro+',
        'Oppo Reno 6',
        'Oppo Reno 6 Pro',
        'Oppo Reno 6 Pro+',
        'Oppo Reno 7',
        'Oppo Reno 7 Pro',
        'Oppo Reno 8',
        'Oppo Reno 8 Pro',
        'Oppo Reno 9',
        'Oppo Reno 9 Pro',
        'Oppo Reno 10',
        'Oppo Reno 10 Pro'
    ],

    'oppo_a' => [
        'Oppo A1',
        'Oppo A3',
        'Oppo A5',
        'Oppo A7',
        'Oppo A9',
        'Oppo A11',
        'Oppo A12',
        'Oppo A31',
        'Oppo A33',
        'Oppo A53',
        'Oppo A54',
        'Oppo A55',
        'Oppo A72',
        'Oppo A73',
        'Oppo A74',
        'Oppo A83',
        'Oppo A91',
        'Oppo A92',
        'Oppo A93',
        'Oppo A95',
        'Oppo A96',
        'Oppo A97',
        'Oppo A78'
    ],


    'huawei_p' => [
        'Huawei P6',
        'Huawei P7',
        'Huawei P8',
        'Huawei P9',
        'Huawei P9 Lite',
        'Huawei P10',
        'Huawei P10 Lite',
        'Huawei P20',
        'Huawei P20 Lite',
        'Huawei P20 Pro',
        'Huawei P30',
        'Huawei P30 Lite',
        'Huawei P30 Pro',
        'Huawei P40',
        'Huawei P40 Lite',
        'Huawei P40 Pro',
        'Huawei P50',
        'Huawei P50 Pro',
        'Huawei P60',
        'Huawei P60 Pro'
    ],

    'huawei_mate' => [
        'Huawei Mate 7',
        'Huawei Mate 8',
        'Huawei Mate 9',
        'Huawei Mate 9 Pro',
        'Huawei Mate 10',
        'Huawei Mate 10 Pro',
        'Huawei Mate 20',
        'Huawei Mate 20 Pro',
        'Huawei Mate 20 X',
        'Huawei Mate 30',
        'Huawei Mate 30 Pro',
        'Huawei Mate 40',
        'Huawei Mate 40 Pro',
        'Huawei Mate 50',
        'Huawei Mate 50 Pro'
    ],

    'huawei_nova' => [
        'Huawei Nova',
        'Huawei Nova Plus',
        'Huawei Nova 2',
        'Huawei Nova 2 Plus',
        'Huawei Nova 3',
        'Huawei Nova 3i',
        'Huawei Nova 4',
        'Huawei Nova 5',
        'Huawei Nova 5i',
        'Huawei Nova 5 Pro',
        'Huawei Nova 6',
        'Huawei Nova 6 SE',
        'Huawei Nova 7',
        'Huawei Nova 7 SE',
        'Huawei Nova 8',
        'Huawei Nova 8 Pro',
        'Huawei Nova 9',
        'Huawei Nova 9 SE'
    ],


    'honor' => [
        'Honor 6',
        'Honor 7',
        'Honor 8',
        'Honor 8 Pro',
        'Honor 9',
        'Honor 10',
        'Honor View 10',
        'Honor 20',
        'Honor 20 Pro',
        'Honor 30',
        'Honor 30 Pro',
        'Honor 30 Lite',
        'Honor V30',
        'Honor V30 Pro',
        'Honor 50',
        'Honor 50 Lite',
        'Honor 50 Pro',
        'Honor 70',
        'Honor 70 Pro',
        'Honor 90',
        'Honor 90 Lite',
        'Honor X1',
        'Honor X2',
        'Honor X3',
        'Honor X4',
        'Honor X5',
        'Honor X6',
        'Honor X7',
        'Honor X8',
        'Honor X9',
        'Honor X10',
        'Honor X20'
    ],


    'google_pixel' => [
        'Google Pixel',
        'Google Pixel XL',
        'Google Pixel 2',
        'Google Pixel 2 XL',
        'Google Pixel 3',
        'Google Pixel 3 XL',
        'Google Pixel 3a',
        'Google Pixel 3a XL',
        'Google Pixel 4',
        'Google Pixel 4 XL',
        'Google Pixel 4a',
        'Google Pixel 4a 5G',
        'Google Pixel 5',
        'Google Pixel 5a',
        'Google Pixel 6',
        'Google Pixel 6 Pro',
        'Google Pixel 6a',
        'Google Pixel 7',
        'Google Pixel 7 Pro',
        'Google Pixel 8',
        'Google Pixel 8 Pro'
    ],


    'tcl' => [
        'TCL 10 SE',
        'TCL 10 L',
        'TCL 10 Pro',
        'TCL 10 Plus',
        'TCL 20 SE',
        'TCL 20 L',
        'TCL 20 Pro 5G',
        'TCL 20S',
        'TCL 30',
        'TCL 30+',
        'TCL 30 XE 5G',
        'TCL 40 XL',
        'TCL 40 5G',
        'TCL 40 SE',
        'TCL 50',
        'TCL 50 5G',
        'TCL 55 5G',
        'TCL 60 5G'
    ],



];
